load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "libs",
    deps = [
        "//libs/vhdx_handler:vhdx_handler",
        "//libs/img_handler:img_handler",
        "//libs/restore:restore"
        ],
    visibility = ["//visibility:public"]
)